spring:
  # db
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/lcn-mall?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: github:lcn29

logging:
  file:
    path: F:\StarMeteoritePavilion\log\mall
